In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv("glass.csv")


In [ ]:
df.shape


(214, 10)

In [ ]:
df.columns


Index(['RI', 'Na', 'Mg', 'Al', 'Si', 'K', 'Ca', 'Ba', 'Fe', 'Type'], dtype='object')

In [ ]:
df.head()


,RI,Na,Mg,Al,Si,K,Ca,Ba,Fe,Type
0,1.52101,13.64,4.49,1.10,71.78,0.06,8.75,0.0,0.0,1
1,1.51761,13.89,3.60,1.36,72.73,0.48,7.83,0.0,0.0,1
2,1.51618,13.53,3.55,1.54,72.99,0.39,7.78,0.0,0.0,1
3,1.51766,13.21,3.69,1.29,72.61,0.57,8.22,0.0,0.0,1
4,1.51742,13.27,3.62,1.24,73.08,0.55,8.07,0.0,0.0,1


type is the output label here

In [ ]:
df["y"] = (df["Type"] == 1).astype(int)
df[["Type", "y"]].head()


,Type,y
0,1,1
1,1,1
2,1,1
3,1,1
4,1,1


In [ ]:
df = df.drop(columns=["Type"])


In [ ]:
X = df.drop(columns=["y"]).values
y = df["y"].values
X.shape, y.shape


((214, 9), (214,))

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
X_train.shape, X_test.shape, y_train.shape, y_test.shape


((171, 9), (43, 9), (171,), (43,))

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
X_train.mean(axis=0)


array([-5.84327908e-18,  1.42835711e-17, -4.75983775e-17, -6.49253231e-18,
       -2.85671422e-17, -1.36343178e-17,  5.84327908e-18, -2.59701292e-17,
        1.27253633e-16])

In [ ]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))
sigmoid(np.array([-10, -1, 0, 1, 10]))


array([4.53978687e-05, 2.68941421e-01, 5.00000000e-01, 7.31058579e-01,
       9.99954602e-01])

In [ ]:
def predict_proba(X, w, b):
    z = X @ w + b
    p = sigmoid(z)
    return p
w_test = np.zeros(X_train.shape[1])
b_test = 0.0

p_test = predict_proba(X_train[:5], w_test, b_test)
p_test


array([0.5, 0.5, 0.5, 0.5, 0.5])

In [ ]:
def loss(y, p):
    return -np.mean(y * np.log(p) + (1 - y) * np.log(1 - p))


In [ ]:
def update_weights(X, y, w, b, lr):

    p = predict_proba(X, w, b)

    error = p - y

    w = w - lr * (X.T @ error) / len(y)
    b = b - lr * np.mean(error)

    return w, b


In [ ]:
w = np.zeros(X_train.shape[1])
b = 0.0

lr = 0.1
epochs = 100

for _ in range(epochs):
    w, b = update_weights(X_train, y_train, w, b, lr)


In [1]:
def predict_label(p, threshold=0.5):
    return (p >= threshold).astype(int)
